### ISSUE TITLE
Remove TODOs from code

### ISSUE THREAD

**Issue by mgalloy** [NCAR/comp-pipeline#105]
We need to fix or remove all `TODO` tags in the code base.

### Todos

- [x] src/level1/comp_image_geometry.pro:  ; TODO: use FLATEXT in header to give the appropriate flat/header for this
- [x] src/level1/comp_l1_mask.pro:    ; TODO: does it need to subtract 1 ?
- [x] src/level1/comp_continuum_correction.pro:      ; TODO: get final keyword names and comments
- [x] src/level1/comp_read_flats.pro:    ; TODO: this should use a better masking for the flat does not properly
- [x] src/level1/comp_radial_der.pro:    ; TODO: remove when done
- [x] src/level1/comp_extract_beams.pro:    ; TODO: check COMP_DISK_MASK for images not centered?
- [x] src/level1/comp_make_header.pro:  ; TODO: should check that exposure is 250.0 ms, might not work if not
- [x] src/level1/comp_apply_flats_darks.pro:    ; TODO: add keyword indicating BAD
- [x] src/level1/comp_promote_primary_header_l1.pro:  ; TODO  sxaddpar, primary_header, 'SOLAR_L0', l0, ' [degrees] L Angle'
- [x] src/level1/comp_l1_process_file.pro:  ; TODO: do uncorrected_images need to be demodulated and corrected for
- [x] src/level1/comp_make_flat.pro:    ; TODO: remove when done
- [x] src/level1/comp_fix_trend.pro:; :Todo: *don't call this routine with default configuration*
- [x] src/level1/comp_fix_trend.pro:; TODO check that center changes are included properly *don't call this routine with default configuration*
- [x] src/level1/comp_find_flat_initial_guess.pro:  ; TODO: this threshold should be a function of time and exposure
- [x] src/level1/comp_demodulate.pro:        ; TODO: this code assumes NAVERAGE is the same for ipheads and impheads
- [x] src/level1/comp_calibrate_wavelength_2.pro:      ; TODO: plot data and fit to continuum was originally here
- [x] src/level1/comp_calibrate_wavelength_2.pro:      ; TODO: next round of plots was originally here
- [x] src/level1/comp_lookup_continuum_correction.pro:    ; TODO: p1[1] = ?, is it data[2, 2 * f]? *don't call this routine*
- [x] src/level1/comp_lookup_continuum_correction.pro:      ; TODO: p1[2] = ?, is it 1.0? *don't call this routine
- [x] src/level2/comp_l2_analytical.pro:    ; TODO: use whatever is in intensity extension for dynamics file for this
- [x] src/level2/comp_l2_analytical.pro:      ; TODO: use fit to correct instead of below
- [x] src/level2/comp_average.pro:; :Todo:
- [x] src/level2/comp_average.pro:      ; TODO: create primary_header, headers and back_headers
- [x] src/level2/comp_average.pro:      ; TODO: comp_update_polarimetric_correction, primary_header, data, headers
- [x] src/level2/comp_average.pro:      ; TODO: may have to reform back to be (x, y, n_images) and then back
- [x] src/level2/comp_average.pro:      ; TODO: comp_update_polarimetric_correction, primary_header, back, back_headers
- [x] src/level2/comp_average.pro:          ; TODO: ?
- [x] src/level2/comp_doppler_correction.pro:  ; TODO: detoma suggestions:
- [x] src/level2/comp_doppler_correction.pro:  ; TODO: use rest wavelength from continuum correction
- [x] src/level2/comp_doppler_correction.pro:  ; TODO: find E and W limb medians inside mask (over occulted by 10 pixels on
- [x] src/level2/comp_doppler_correction.pro:    ; TODO: adjust this constant
- [x] src/level2/comp_doppler_correction.pro:  ; TODO: adjust filter to help fit?
- [x] src/level2/comp_doppler_correction.pro:    ; TODO: make sure fit is better at the edges, change order?
- [x] src/level2/comp_find_systematics.pro:    ; TODO: why the next line? It modifies dat, which is not used again until
- [x] src/level2/comp_quick_invert.pro:  ; TODO: should this be divided by sqrt(2.0) to give sigma?
- [x] src/level2/comp_quick_invert.pro:  ; TODO: not using this corrected_dop right now
- [x] src/level2/comp_quick_invert.pro:  ; TODO: geometric mask?
- [x] src/level2/comp_quick_invert.pro:    ; TODO: use fit to correct instead of below
- [x] src/database/comp_mission.tbl:-- TODO: ask Steve: are there any instrument hardware changes that need to be
- [x] src/database/comp_file_insert.pro:  ; TODO: what is quality?
- [ ] src/database/comp_db_clearday.pro:  ; TODO: clear entries based on what will be created in the current run from
- [ ] src/comp_reprocess.pro:  ; TODO: delete files based on what will be created in the current run from

**Comment by mgalloy** [comment]
Here are all the TODOs:

```
comp-pipeline$ grep -ir TODO src
src/level1/comp_image_geometry.pro:  ; TODO: use FLATEXT in header to give the appropriate flat/header for this
src/level1/comp_l1_mask.pro:    ; TODO: does it need to subtract 1 ?
src/level1/comp_continuum_correction.pro:      ; TODO: get final keyword names and comments
src/level1/comp_read_flats.pro:    ; TODO: this should use a better masking for the flat does not properly
src/level1/comp_radial_der.pro:    ; TODO: remove when done
src/level1/comp_extract_beams.pro:    ; TODO: check COMP_DISK_MASK for images not centered?
src/level1/comp_make_header.pro:  ; TODO: should check that exposure is 250.0 ms, might not work if not
src/level1/comp_apply_flats_darks.pro:    ; TODO: add keyword indicating BAD
src/level1/comp_promote_primary_header_l1.pro:  ; TODO  sxaddpar, primary_header, 'SOLAR_L0', l0, ' [degrees] L Angle'
src/level1/comp_l1_process_file.pro:  ; TODO: do uncorrected_images need to be demodulated and corrected for
src/level1/comp_make_flat.pro:    ; TODO: remove when done
src/level1/comp_fix_trend.pro:; :Todo:
src/level1/comp_fix_trend.pro:; TODO check that center changes are included properly
src/level1/comp_find_flat_initial_guess.pro:  ; TODO: this threshold should be a function of time and exposure
src/level1/comp_demodulate.pro:        ; TODO: this code assumes NAVERAGE is the same for ipheads and impheads
src/level1/comp_calibrate_wavelength_2.pro:      ; TODO: plot data and fit to continuum was originally here
src/level1/comp_calibrate_wavelength_2.pro:      ; TODO: next round of plots was originally here
src/level1/comp_lookup_continuum_correction.pro:    ; TODO: p1[1] = ?, is it data[2, 2 * f]?
src/level1/comp_lookup_continuum_correction.pro:      ; TODO: p1[2] = ?, is it 1.0?
src/level2/comp_l2_analytical.pro:    ; TODO: use whatever is in intensity extension for dynamics file for this
src/level2/comp_l2_analytical.pro:      ; TODO: use fit to correct instead of below
src/level2/comp_average.pro:; :Todo:
src/level2/comp_average.pro:      ; TODO: create primary_header, headers and back_headers
src/level2/comp_average.pro:      ; TODO: comp_update_polarimetric_correction, primary_header, data, headers
src/level2/comp_average.pro:      ; TODO: may have to reform back to be (x, y, n_images) and then back
src/level2/comp_average.pro:      ; TODO: comp_update_polarimetric_correction, primary_header, back, back_headers
src/level2/comp_average.pro:          ; TODO: ?
src/level2/comp_doppler_correction.pro:  ; TODO: detoma suggestions:
src/level2/comp_doppler_correction.pro:  ; TODO: use rest wavelength from continuum correction
src/level2/comp_doppler_correction.pro:  ; TODO: find E and W limb medians inside mask (over occulted by 10 pixels on
src/level2/comp_doppler_correction.pro:    ; TODO: adjust this constant
src/level2/comp_doppler_correction.pro:  ; TODO: adjust filter to help fit?
src/level2/comp_doppler_correction.pro:    ; TODO: make sure fit is better at the edges, change order?
src/level2/comp_find_systematics.pro:    ; TODO: why the next line? It modifies dat, which is not used again until
src/level2/comp_quick_invert.pro:  ; TODO: should this be divided by sqrt(2.0) to give sigma?
src/level2/comp_quick_invert.pro:  ; TODO: not using this corrected_dop right now
src/level2/comp_quick_invert.pro:  ; TODO: geometric mask?
src/level2/comp_quick_invert.pro:    ; TODO: use fit to correct instead of below
src/database/comp_mission.tbl:-- TODO: ask Steve: are there any instrument hardware changes that need to be
src/database/comp_file_insert.pro:  ; TODO: what is quality?
src/database/comp_db_clearday.pro:  ; TODO: clear entries based on what will be created in the current run from
src/comp_reprocess.pro:  ; TODO: delete files based on what will be created in the current run from
```

**Comment by detoma** [comment]
Some need to be addressed. let's go over them at the next COMP meeting.

**Comment by mgalloy** [comment]
- [ ] src/level1/comp_image_geometry.pro:  ; TODO: use FLATEXT in header to give the appropriate flat/header for this
- [ ] src/level1/comp_l1_mask.pro:    ; TODO: does it need to subtract 1 ?
- [ ] src/level1/comp_continuum_correction.pro:      ; TODO: get final keyword names and comments
- [ ] src/level1/comp_read_flats.pro:    ; TODO: this should use a better masking for the flat does not properly
- [ ] src/level1/comp_radial_der.pro:    ; TODO: remove when done
- [ ] src/level1/comp_extract_beams.pro:    ; TODO: check COMP_DISK_MASK for images not centered?
- [ ] src/level1/comp_make_header.pro:  ; TODO: should check that exposure is 250.0 ms, might not work if not
- [ ] src/level1/comp_apply_flats_darks.pro:    ; TODO: add keyword indicating BAD
- [ ] src/level1/comp_promote_primary_header_l1.pro:  ; TODO  sxaddpar, primary_header, 'SOLAR_L0', l0, ' [degrees] L Angle'
- [ ] src/level1/comp_l1_process_file.pro:  ; TODO: do uncorrected_images need to be demodulated and corrected for
- [ ] src/level1/comp_make_flat.pro:    ; TODO: remove when done
- [ ] src/level1/comp_fix_trend.pro:; :Todo:
- [ ] src/level1/comp_fix_trend.pro:; TODO check that center changes are included properly
- [ ] src/level1/comp_find_flat_initial_guess.pro:  ; TODO: this threshold should be a function of time and exposure
- [ ] src/level1/comp_demodulate.pro:        ; TODO: this code assumes NAVERAGE is the same for ipheads and impheads
- [ ] src/level1/comp_calibrate_wavelength_2.pro:      ; TODO: plot data and fit to continuum was originally here
- [ ] src/level1/comp_calibrate_wavelength_2.pro:      ; TODO: next round of plots was originally here
- [ ] src/level1/comp_lookup_continuum_correction.pro:    ; TODO: p1[1] = ?, is it data[2, 2 * f]?
- [ ] src/level1/comp_lookup_continuum_correction.pro:      ; TODO: p1[2] = ?, is it 1.0?
- [ ] src/level2/comp_l2_analytical.pro:    ; TODO: use whatever is in intensity extension for dynamics file for this
- [ ] src/level2/comp_l2_analytical.pro:      ; TODO: use fit to correct instead of below
- [ ] src/level2/comp_average.pro:; :Todo:
- [ ] src/level2/comp_average.pro:      ; TODO: create primary_header, headers and back_headers
- [ ] src/level2/comp_average.pro:      ; TODO: comp_update_polarimetric_correction, primary_header, data, headers
- [ ] src/level2/comp_average.pro:      ; TODO: may have to reform back to be (x, y, n_images) and then back
- [ ] src/level2/comp_average.pro:      ; TODO: comp_update_polarimetric_correction, primary_header, back, back_headers
- [ ] src/level2/comp_average.pro:          ; TODO: ?
- [ ] src/level2/comp_doppler_correction.pro:  ; TODO: detoma suggestions:
- [ ] src/level2/comp_doppler_correction.pro:  ; TODO: use rest wavelength from continuum correction
- [ ] src/level2/comp_doppler_correction.pro:  ; TODO: find E and W limb medians inside mask (over occulted by 10 pixels on
- [ ] src/level2/comp_doppler_correction.pro:    ; TODO: adjust this constant
- [ ] src/level2/comp_doppler_correction.pro:  ; TODO: adjust filter to help fit?
- [ ] src/level2/comp_doppler_correction.pro:    ; TODO: make sure fit is better at the edges, change order?
- [ ] src/level2/comp_find_systematics.pro:    ; TODO: why the next line? It modifies dat, which is not used again until
- [ ] src/level2/comp_quick_invert.pro:  ; TODO: should this be divided by sqrt(2.0) to give sigma?
- [ ] src/level2/comp_quick_invert.pro:  ; TODO: not using this corrected_dop right now
- [ ] src/level2/comp_quick_invert.pro:  ; TODO: geometric mask?
- [ ] src/level2/comp_quick_invert.pro:    ; TODO: use fit to correct instead of below
- [ ] src/database/comp_mission.tbl:-- TODO: ask Steve: are there any instrument hardware changes that need to be
- [ ] src/database/comp_file_insert.pro:  ; TODO: what is quality?
- [ ] src/database/comp_db_clearday.pro:  ; TODO: clear entries based on what will be created in the current run from
- [ ] src/comp_reprocess.pro:  ; TODO: delete files based on what will be created in the current run from

**Comment by detoma** [comment]
All TODO for the level2 processing have were examined and resolved.

**Comment by mgalloy** [comment]
For `src/level1/comp_fix_trend.pro` and `src/level1/comp_lookup_continuum_correction.pro`, these routines are not called when we run the pipeline now, so we are OK now. I left the TODOs in the code because they would need to be addressed if we changed configuration options.
