### ISSUE TITLE
Create IQUV all images

### ISSUE THREAD

**Issue by mgalloy** [NCAR/comp-pipeline#147]
Create a GIF/PNG similar to UCoMP's "IQUV all" images, i.e., all wavelengths and polarizations in a level 1 file.

#### Tasks

- [x] create routine to produce the IQUV all image for a given level 1 filename
- [x] create script to make IQUV all images for existing dates
- [x] create IQUV all images for existing level 1 data
- [x] add creation of IQUV all images to pipeline
- [x] remove existing 1083 IQUV all images

#### Creating IQUV all images for existing level 1 data

- [x] 2012
- [x] 2013
- [x] 2014
- [x] 2015
- [x] 2016
- [x] 2017
- [x] 2018

**Comment by mgalloy** [comment]
Below is an example image. Note: GitHub will resize image a bit to make it fit into the width of these comments.

![20110309 185203 comp 1074 iv 3 all](https://github.com/NCAR/comp-pipeline/assets/713524/0c3105cd-d151-4161-b640-266dcd1d8a67)

**Comment by detoma** [comment]
This looks good. Let's discuss tomorrow min and max.

**Comment by mgalloy** [comment]
I have created IQUV all images for the test dates from #150.

**Comment by detoma** [comment]
These are very instructive for 1074 and 1079. For 10830 they are not useful because the exposure, ND filter changes too much and there is no useful signal in q u v.

Let's make these products only for 1074 and 1079.
