### ISSUE TITLE
Update flat threshold in ucomp_make_flat

### ISSUE THREAD

**Issue by mgalloy** [NCAR/comp-pipeline#158]
The calculation of the minimum threshold for the median of flats is currently computed via line 337 of `ucomp_make_flat.pro`:

```
threshold = (norm - min_flat_median_offset) * expose / 250.0 / transmission_correction
```

where `norm` is the transmission computed for the day with `comp_transmission` and `min_flat_median_offset` is an epoch value that is currently always 20.0.

But the median of the flat image has been normalized already, so `norm - min_flat_median_offset` shouldn't be a function of date. So the threshold should be computed:

```
threshold = min_flat_median_offset * expose / 250.0 / transmission_correction
```

where `min_flat_median_offset` has a constant value. We need to find this value through analysis of the flat medians.

Note, by 20110622, there are not as many flats currently marked as bad, and the bad ones are just barely bad, from the logs from 20110622:

```
  38.60 (flat median) < 38.86 (minimum theshold)
  38.82 (flat median) < 38.86 (minimum theshold)
  38.85 (flat median) < 38.86 (minimum theshold)
```

#### Tasks

- [ ] update equation for calculation of minimum threshold for flats
- [ ] analyze statistical properties of the normalized (corrected by `ucomp_transmission`) median flat values — they should be roughly constant over the mission
- [ ] determine new `min_flat_median_offset` value

**Comment by mgalloy** [comment]
Below is the most recent flat medians plot.

[flat-medians-20201222.pdf](https://github.com/NCAR/comp-pipeline/files/15407893/flat-medians-20201222.pdf)

**Comment by mgalloy** [comment]
Before 2016, 70.0 should be minimum transmission corrected values. After 2016, 60.0 should be good.

**Comment by mgalloy** [comment]
I have the code ready to create all the darks/flats again and log differences in the passing by the old and new thresholds. I will need to untar each month of raw data as the processing progresses.
